version: '3.7'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - 8888:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mysql
      - php
    networks:
      - laravel
    
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: blankfactor
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: bfuser
      MYSQL_PASSWORD: bfpassword
    ports:
      - 3307:3306
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - laravel

  php:      
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    ports:
      - 9000:80
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel

networks:
  laravel:
